name: Execute

on:
    workflow_dispatch:
        inputs:
            manifests:
                description: 'Manifests to use (must contain full path)'
                required: false
                default: ''

jobs:
    execute:
        runs-on: executor
        environment: Execution
        steps:
            -   name: RUN
                run: docker run --pull always -v "/var/run/docker.sock":"/var/run/docker.sock" -v trash:/data/git_folder -v dd_data:/data/.local/share/IsolatedStorage -v /data/manifests:/data/manifests -e SSH_KEY="${{ secrets.SSH_KEY }}" -e GIT_NAME="${{ secrets.GIT_NAME }}" -e GIT_EMAIL="${{ secrets.GIT_EMAIL }}" -e GIT_URL="${{ secrets.GIT_URL }}" -e GPG_KEY="${{ secrets.GPG_KEY }}" -e GPG_KEY_ID="${{ secrets.GPG_KEY_ID }}" -e KNOWN_HOSTS='${{ secrets.KNOWN_HOSTS }}' -e MANIFESTS="${{ inputs.manifests }}" -e STEAM_USERNAME="${{ secrets.STEAM_USERNAME }}" -e STEAM_PASSWORD='${{ secrets.STEAM_PASSWORD }}' ghcr.io/lifeismana/ddlck-vpk-decompiler:latest